Gem::Specification.new do |s|
  s.name = 'logstash-codec-perf4j-coalescing'
  s.version = '0.2.2'
  s.licenses = ['Apache License (2.0)']
  s.summary = "This codec handles input of performance log files generated by perf4j's AsyncCoalescingStatisticsAppender in Logstash"
  s.description = "This gem is a logstash plugin required to be installed on top of the Logstash core pipeline using $LS_HOME/bin/plugin install gemname. This gem is not a stand-alone program"
  s.authors = ["Mattias Ohlsson"]
  s.email = ''
  s.homepage = ""
  s.require_paths = ["lib"]

  # Files
  s.files = Dir['lib/**/*','spec/**/*','vendor/**/*','*.gemspec','*.md','CONTRIBUTORS','Gemfile','LICENSE','NOTICE.TXT']
   # Tests
  s.test_files = s.files.grep(%r{^(test|spec|features)/})

  # Special flag to let us know this is actually a logstash plugin
  s.metadata = { "logstash_plugin" => "true", "logstash_group" => "codec" }

  # Gem dependencies
  s.add_runtime_dependency "logstash-core", ">= 2.0.0", "< 3.0.0"

  s.add_runtime_dependency 'logstash-codec-line', '>= 2.1.0'

  s.add_development_dependency 'logstash-devutils'
end
